#!/usr/bin/gawk -f
# 21_Gsub_SELECT_RENSEIGNEMENTS_SUR_LE_SITE_Page_d_accueil_CODES_DE_HACHAGE.awk
# gawk -f AWKScript/21_Gsub_SELECT_RENSEIGNEMENTS_SUR_LE_SITE_Page_d_accueil_CODES_DE_HACHAGE.awk  -v CODE_D_IDENTIFICATION=CODE_D_IDENTIFICATION -v CODES_DE_HACHAGE=CODES_DE_HACHAGE SQLScript/02_SELECT_RENSEIGNEMENTS_SUR_LE_SITE_Page_d_accueil.sql > SQLScript/01_INSERT_RENSEIGNEMENTS_SUR_LE_SITE_Page_d_accueil2.sql

BEGIN{
	if(CODE_D_IDENTIFICATION == ""){
		CODE_D_IDENTIFICATION = "FACTICE";
	}
	if(CODES_DE_HACHAGE == ""){
		CODES_DE_HACHAGE = "FACTICE";
	}
	
	DATE_ET_HEURE_D_ACQUISITION = strftime("%Y-%m-%d", systime())" 00:00:00";
}

{
	gsub(":CODE_D_IDENTIFICATION", CODE_D_IDENTIFICATION);
	gsub(":DATE_ET_HEURE_D_ACQUISITION", DATE_ET_HEURE_D_ACQUISITION);
	gsub(":CODES_DE_HACHAGE", CODES_DE_HACHAGE);
	print;
}

