-- 02_SELECT_RENSEIGNEMENTS_SUR_LE_SITE_Page_d_accueil.sql
-- SQLScript/02_SELECT_RENSEIGNEMENTS_SUR_LE_SITE_Page_d_accueil.sql
.bail on
.output stdout

.parameter init
.parameter set @CODE_D_IDENTIFICATION "':CODE_D_IDENTIFICATION'"
.parameter set @DATE_ET_HEURE_D_ACQUISITION "':DATE_ET_HEURE_D_ACQUISITION'"
.parameter set @BALISE_ENTITE_ETAG_HTTP "':BALISE_ENTITE_ETAG_HTTP'"

SELECT
	COUNT(*) AS CNT
FROM
	RENSEIGNEMENTS_SUR_LE_SITE
WHERE
	CODE_D_IDENTIFICATION = @CODE_D_IDENTIFICATION
AND
	DATE_ET_HEURE_D_ACQUISITION = @DATE_ET_HEURE_D_ACQUISITION
AND
	BALISE_ENTITE_ETAG_HTTP = @BALISE_ENTITE_ETAG_HTTP
;

