-- 10_SELECT_RENSEIGNEMENTS_SUR_LE_SITE_Page_d_accueil_CODES_DE_HACHAGE_PRESTATIONS_D_AIDE_AU_LOYER.sql
-- SQLScript/10_SELECT_RENSEIGNEMENTS_SUR_LE_SITE_Page_d_accueil_CODES_DE_HACHAGE_PRESTATIONS_D_AIDE_AU_LOYER.sql
.bail on
.output stdout

.parameter init
.parameter set @CODE_D_IDENTIFICATION "':CODE_D_IDENTIFICATION'"
.parameter set @DATE_ET_HEURE_D_ACQUISITION "':DATE_ET_HEURE_D_ACQUISITION'"
.parameter set @CODES_DE_HACHAGE "':CODES_DE_HACHAGE'"

SELECT
	COUNT(*) AS CNT
FROM
	RENSEIGNEMENTS_SUR_LE_SITE_PRESTATIONS_D_AIDE_AU_LOYER
WHERE
	CODE_D_IDENTIFICATION = @CODE_D_IDENTIFICATION
AND
	DATE_ET_HEURE_D_ACQUISITION = @DATE_ET_HEURE_D_ACQUISITION
AND
	CODES_DE_HACHAGE = @CODES_DE_HACHAGE
;

