-- 13_RESET.sql
-- SQLScript/13_RESET.sql
.bail on
.output stdout

BEGIN TRANSACTION;

DELETE FROM RENSEIGNEMENTS_SUR_LE_SITE;
DELETE FROM LISTE_DE_CERTIFICATION_DES_BENEFICIAIRES_FRAUDULEUX_POUR_LES_ENTREPRISES;
DELETE FROM LISTE_DE_CERTIFICATION_DES_BENEFICIAIRES_FRAUDULEUX_POUR_LES_TRAVAILLEURS_INDEPENDANTS;

COMMIT;

